// <auto-generated />
namespace TakeAction.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddedManagerFullNameToTask : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedManagerFullNameToTask));
        
        string IMigrationMetadata.Id
        {
            get { return "202104251417260_AddedManagerFullNameToTask"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
